//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaySeoul_SS2Api.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemPrice()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public long ID { get; set; }
        public string itemTitle { get; set; }
        public System.Guid GUID { get; set; }
        public long ItemID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public long CancellationPolicyID { get; set; }
        public decimal holidayPrice { get; set; }
        public decimal weekendPrice { get; set; }
        public long normalCancellationPolicy { get; set; }
        public long weekendCancellationPolicy { get; set; }
        public long holidayCancellationPolicy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual CancellationPolicy CancellationPolicy { get; set; }
        public virtual Item Item { get; set; }
       

    }
}
